name: R CI

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_github("damarals/letras")

      - name: Run a script
        run: |
          R -e "library(letras)"
