name: R CI

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools and letras
        run: |
          R -e 'install.packages("devtools", repos = "https://cloud.r-project.org/")'
          R -e 'devtools::install_github("damarals/letras")'

      - name: Test letras
        run: |
          R -e 'library(letras)'
